language: go

go:
  - "1.10"

sudo: required

install: ./Travis/install.sh

script: ./Travis/script.sh

before_deploy: ./Travis/before_deploy.sh

deploy:
  # Deploy a nightly build.
  - provider: script
    script: bash ./Travis/deploy_nightly.sh
    skip-cleanup: true
    on:
      branch: master
  # Deploy a new LIKO-12 release.
  - provider: script
    script: bash ./Travis/deploy_release.sh
    skip-cleanup: true
    on:
      tags: true
