language: cpp

sudo: required

git:
  depth: false

branches:
  only:
  - master

install: ./Extra/Travis/install.sh

script: ./Extra/Travis/script.sh

before_deploy: ./Extra/Travis/before_deploy.sh

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: ../BuildUtils/Builds/
  repo: RamiLego4Game/LIKO-12-Nightly
