site_name: LIKO-12
repo_url: https://github.com/RamiLego4Game/LIKO-12/
repo_name: GitHub
edit_uri: edit/WIP/Docs/
site_description: The official LIKO-12 documentation.
site_author: Rami Sabbagh (RamiLego4Game)
theme: readthedocs
docs_dir: 'Docs'
extra:
 version: '0.8.0'